version: 0.0
os: linux
files:
    - source: .
      destination: /home/elbarae/messenger-backend
hooks:
    AfterInstall:
        - location: .aws/after_install.sh
          timeout: 300
          runas: elbarae
    ApplicationStart:
        - location: .aws/application_start.sh
          timeout: 300
          runas: elbarae
