version: 0.0
os: linux
files:
    - source: .
      destination: /home/elbarae/messenger-backend
hooks:
    AfterInstall:
        - location: .aws/update_image.sh
          timeout: 300
          runas: elbarae
    ApplicationStart:
        - location: .aws/restart_container.sh
          timeout: 300
          runas: elbarae