# compose file for running the database only

version: '3.7'

services:
  messenger_db:
    container_name: messenger_db
    image: postgres:13
    volumes:
        - pgdata:/var/lib/postgresql/data:delegated
    ports:
      - ${POSTGRES_PORT}:5432
    env_file: .env

  redis:
    container_name: messenger_redis
    image: redis:latest
    ports:
      - ${REDIS_PORT}:6379
    env_file: .env

volumes:
  pgdata:
