version: '3.7'

services:
  messenger_db:
    container_name: messenger_db
    image: postgres:13
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data:delegated
    ports:
      - 5431:5432
    env_file: .env.prod
    networks:
      - messenger_net

  messenger-graphql:
    container_name: messenger-graphql
    restart: always
    image: ghcr.io/elbarae1921/mgraphql:latest
    env_file: packages/mgraphql/.env.prod
    ports:
      - 4000:4000
    external_links:
      - messenger_db
    depends_on:
      - messenger_db
    networks:
      - messenger_net

volumes:
  pgdata:

networks:
  messenger_net:
    driver: bridge
