# compose file for running the app in production

version: '3.7'

services:
  messenger_db:
    container_name: messenger_db
    image: postgres:13
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data:delegated
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file: .env
    networks:
      - messenger_net

  messenger:
    container_name: messenger
    restart: always
    build: .
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    external_links:
      - messenger_db
    depends_on:
      - messenger_db
    networks:
      - messenger_net

volumes:
  pgdata:

networks:
  messenger_net:
    driver: bridge