name: Build and Deploy
on:
  push:
    tags:
      - "v**.**.**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      # Step 1
      - uses: actions/checkout@v2
      # Step 2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Step 3
      - name: Build shared docker image
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/elbarae1921/messenger-shared:latest,ghcr.io/elbarae1921/messenger-shared:${{ github.event.release.tag_name }}
          file: Dockerfile.shared
          push: true
          cache-from: type=registry,ref=ghcr.io/elbarae1921/messenger-shared:latest
          cache-to: type=inline
      # Step 4
      - name: Build & publish graphql server
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/elbarae1921/mgraphql:latest,ghcr.io/elbarae1921/mgraphql:${{ github.event.release.tag_name }}
          push: true
          context: ./packages/mgraphql
          cache-from: type=registry,ref=ghcr.io/elbarae1921/mgraphql:latest
          cache-to: type=inline
      # Step 6
      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: TODO
      # Step 5
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      # Step 6
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name skeduler-deploy \
            --deployment-group-name SkedulerDeploymentGroup \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
