name: Test
on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - uses: actions/checkout@v2
      # Step 2
      - name: Set up Node 16.x
        uses: actions/setup-node@v2
        with:
            node-version: 16.x
      # Step 3
      - name: Install dependencies
        run: yarn
      # Step 5
      - name: Lint
        run: yarn lint
      # Step 7
      - name: Build
        run: yarn build
      # Step 6
      - name: Run tests
        run: yarn test
